use modificar;
create table pruebauno;
alter table pruebauno rename pruebados;
show tables;
describe pruebados;
describe abc;
alter table abc drop column altura;
describe abc;
alter table pk add (edad int);
describe pk;
alter table pk drop primary key;
alter table pk add (peso double);
describe pk;
alter table pk add estatura double after peso;
describe pk;
alter table pk drop column estatura;
alter table pk add altura double first;
describe pk;
alter table pk modify column edad int default 18;
describe pk;
alter table pk add primary key (id);
alter table pk modify column id int auto_increment;
alter table pk auto_increment=2;
describe pk;
insert into pk (altura, edad, peso) values (1.80, 20, 68.50);
select * from pk;
